### ISSUE TITLE
Error Fetching Course Assignments: JSON Syntax Error

### ISSUE THREAD

**Issue by HakeemsGit** [kiat/codeAssist#58]
Issue: Fetching course assignments fails with SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON at index.js:161.

Expected Behavior: JSON data for course assignments should be fetched and parsed correctly.

Actual Behavior: Fetch operation fails, suggesting the response is HTML (not JSON).

Potential Cause: Incorrect endpoint or server configuration issue leading to HTML response.

Steps to Reproduce:

Go to course assignments page.
Initiate fetch operation for assignments.
Suggested Actions:

Confirm endpoint URL correctness.
Check for server-side redirects or authentication issues.
Review the network response in browser dev tools.

**Comment by defkorean** [comment]
Ensure endpoint URL correctness by writing in valid URL in fronend/.env 
Otherwise the above will happen. 

Valid url:
REACT_APP_API_URL=http://localhost:5000 

Note,
if on macOS, there are two options to handle this issue ticket. 

1. Set to a different port i.e localhost:5001
2. Turn off airplay in settings since Flask and airplay share the same port (if your system is on macOS Monterey or later)
